---
title: "Post processing Bus Bunching output file"
author: "Veruska Santos"
date: "10 de novembro de 2018"
output: html_document
---

Processando o arquivo de saída que determina a ocorrência de BB para gerar os arquivos das visualizações.

Importando biblioteca do R a ser usada para ler os dados e manipulá-los.

```{r setup, message=FALSE, warning=FALSE}
library(tidyverse)
library(stringr)
library(tools)
```

Carregando os dados que serão analisados.

```{r read}
gps_shape_data = read.csv(here::here("data/outputBusBunching/outputBusBunching-2017-05-01.csv"))

```

```{r}
local_path = paste(file_path_as_absolute(".."), "/data/outputBusBunching/rPostProcessing/", sep = "")

saveCSV <- function (file, name){
  write.csv(file, paste(local_path, name, ""), row.names=FALSE)
}

```

```{r read}
# Total of bb in each bus trip
bb = gps_shape_data %>%
  mutate(hasBB = busBunching != "")  %>%
  group_by(date, route, tripNum, busCode, hasBB) %>%
  count()

# Removing column total of bus bunching
tripHasBB = bb %>%
  group_by(date, route, tripNum, busCode, hasBB) %>%
  subset(select = -c(n))

# Bus trip with bus bunching or not
route_bus_trip_bb <- setNames(aggregate(tripHasBB$hasBB, by = list(tripHasBB$date, tripHasBB$route, tripHasBB$busCode, tripHasBB$tripNum), max), c("date", "route", "busCode", "tripNum", "hasBusBunching"))
```

## Statistical analysis

- POR DIA
- POR MÊS
- POR DIA DA SEMANA
- POR HORA - OK
- POR ROTA (geral) - OK
- POR ônibus (geral) - OK

### Por rota 

```{r}
# Total of bus bunching per route
bb_per_route <- route_bus_trip_bb %>%
  group_by(date, route) %>%
  mutate(totalTrips = n()) %>% #total of trips
  group_by(date, route, hasBusBunching) %>%
  count(trips = n(), percTrips = trips/totalTrips) %>% #total of trips with bb
  subset(select = -c(n))

bb_per_route$hasBusBunching[bb_per_route$hasBusBunching == 1] <- "TRUE"
bb_per_route$hasBusBunching[bb_per_route$hasBusBunching == 0] <- "FALSE"

bb_per_route

```

```{r}
saveCSV(bb_per_route, 'bb_per_route-2017-05-01.csv')

```

```{r}
length(unique(bb_per_route$route))

routes_with_bb <- bb_per_route %>%
  filter(hasBusBunching == TRUE)

length(unique(routes_with_bb$route))

```
---------------------------

### Por ônibus 

```{r}
# Total of bus bunching per bus
bb_per_bus <- route_bus_trip_bb %>%
  group_by(date, busCode) %>%
  mutate(totalTrips = n()) %>% # total of trips per bus
  group_by(date, busCode, hasBusBunching) %>%
  count(trips = n(), percTrips = trips/totalTrips) %>% #total of trips with bb
  subset(select = -c(n))

bb_per_bus$hasBusBunching[bb_per_bus$hasBusBunching == 1] <- "TRUE"
bb_per_bus$hasBusBunching[bb_per_bus$hasBusBunching == 0] <- "FALSE"

bb_per_bus

```

```{r}
salvarCSV(bb_per_bus, 'bb_per_bus-2017-05-01.csv')

```

```{r}
length(unique(bb_per_bus$busCode))

buses_with_bb <- bb_per_bus %>%
  filter(hasBusBunching == TRUE)

length(unique(buses_with_bb$busCode))

```

-----------------------------------------

### Por hora do dia e rota

```{r read}

# Get hour
gps_shape_data$time <- str_split_fixed(gps_shape_data$time, ":", 2)[,1]

# Total of bb in each bus trip
bb_per_hour = gps_shape_data %>%
  mutate(hasBB = busBunching != "")  %>%
  group_by(date, route, tripNum, busCode, time, hasBB) %>%
  count()

# Removing column total of bus bunching
trip_has_BB_per_hour = bb_per_hour %>%
  group_by(date, route, tripNum, busCode, time, hasBB) %>%
  subset(select = -c(n))

# Bus trip with bus bunching or not
day_route_bus_trip_time_bb <- setNames(aggregate(trip_has_BB_per_hour$hasBB, by = list(trip_has_BB_per_hour$date, trip_has_BB_per_hour$route, trip_has_BB_per_hour$busCode, trip_has_BB_per_hour$tripNum, trip_has_BB_per_hour$time), max), c("date", "route", "busCode", "tripNum", "time", "hasBusBunching"))


# Total of bus bunching per route and hour
trips_per_route_and_hour <- day_route_bus_trip_time_bb %>%
  group_by(date, route, time) %>%
  mutate(totalTrips = n()) %>% #total of trips
  group_by(date, route, time, hasBusBunching) %>%
  count(trips = n(), percTrips = trips/totalTrips) %>% #total of trips with bb
  subset(select = -c(n))

trips_per_route_and_hour$hasBusBunching[trips_per_route_and_hour$hasBusBunching == 1] <- "TRUE"
trips_per_route_and_hour$hasBusBunching[trips_per_route_and_hour$hasBusBunching == 0] <- "FALSE"

# Calculate percentagem of trips with BB
bb_per_route_and_hour <- trips_per_route_and_hour %>%
  filter(hasBusBunching == "FALSE") %>%
  mutate(percTripsWithBB = 1 - percTrips)

names(bb_per_route_and_hour)[names(bb_per_route_and_hour) == 'percTrips'] <- 'percTripsWithoutBB'
bb_per_route_and_hour$hasBusBunching <- TRUE
  

```

```{r}
saveCSV(bb_per_route_and_hour, 'bb_per_route_and_hour-2017-05-01.csv')
```